apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: ak-angular-app
        image: naveen3423/myapp:latest
        ports:
        - containerPort: 8085
        
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: prod-app-svc
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer