apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-app
  template:
    metadata:
      labels:
        app: prod-app
    spec:
      containers:
      - name: prod-app
        image: naveen3423/mywebapp:{{BUILD_NUMBER}}
        ports:
        - containerPort: 8085
        
# service type ClusterIP       
---
apiVersion: v1
kind: Service
metadata:
  name: prod-app
spec:
  selector:
    app: prod-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer
